---
  name: SpigotNotepad
  version: "0.1.1"
  author: Andre LaFleur
  main: usa.alafleur.spigot_notepad.Main
  api-version: "1.14"
  description: Notepad for Minecraft chat client
  commands:
    note:
      description: "Create, read, and delete notes to yourself"
      usage: "/note <add CONTENT | list | read ID | delete ID>"
