---
  name: SpigotNotepad
  version: 0.0.1
  author: Andre LaFleur
  main: usa.alafleur.spigot_notepad.Main
  api-version: "1.14"
  commands:
    note:
      description: "Create, read, and delete notes to yourself"
      usage: "/note <add|list|delete> [-name NAME] <content>"
